# Generated by Django 5.2.8 on 2025-11-10 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bot_username', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_months', models.IntegerField()),
                ('contract_start_date', models.DateTimeField()),
                ('contract_end_date', models.DateTimeField()),
                ('is_renewed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('ExpiringSoon', 'Expiring Soon')], db_index=True, default='Active', max_length=20)),
                ('customer_telegram', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
